source 'https://rubygems.org'

gem 'rake'
gem 'rack'
gem 'json'
gem 'ansi'
gem 'slim'
gem 'nokogiri'
gem 'builder'
#gem 'sqlite3'

gem 'middleman'
gem 'middleman-blog'
#gem 'middleman-blog-similar'
gem 'middleman-minify-html'
gem 'middleman-syntax'
gem 'middleman-robots'
gem 'middleman-sitemap-ping'